// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package openmeteo_sdk

import "strconv"

type Aggregation byte

const (
	Aggregationnone     Aggregation = 0
	Aggregationminimum  Aggregation = 1
	Aggregationmaximum  Aggregation = 2
	Aggregationmean     Aggregation = 3
	Aggregationp10      Aggregation = 4
	Aggregationp25      Aggregation = 5
	Aggregationmedian   Aggregation = 6
	Aggregationp75      Aggregation = 7
	Aggregationp90      Aggregation = 8
	Aggregationdominant Aggregation = 9
	Aggregationsum      Aggregation = 10
	Aggregationspread   Aggregation = 11
)

var EnumNamesAggregation = map[Aggregation]string{
	Aggregationnone:     "none",
	Aggregationminimum:  "minimum",
	Aggregationmaximum:  "maximum",
	Aggregationmean:     "mean",
	Aggregationp10:      "p10",
	Aggregationp25:      "p25",
	Aggregationmedian:   "median",
	Aggregationp75:      "p75",
	Aggregationp90:      "p90",
	Aggregationdominant: "dominant",
	Aggregationsum:      "sum",
	Aggregationspread:   "spread",
}

var EnumValuesAggregation = map[string]Aggregation{
	"none":     Aggregationnone,
	"minimum":  Aggregationminimum,
	"maximum":  Aggregationmaximum,
	"mean":     Aggregationmean,
	"p10":      Aggregationp10,
	"p25":      Aggregationp25,
	"median":   Aggregationmedian,
	"p75":      Aggregationp75,
	"p90":      Aggregationp90,
	"dominant": Aggregationdominant,
	"sum":      Aggregationsum,
	"spread":   Aggregationspread,
}

func (v Aggregation) String() string {
	if s, ok := EnumNamesAggregation[v]; ok {
		return s
	}
	return "Aggregation(" + strconv.FormatInt(int64(v), 10) + ")"
}
