// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package openmeteo_sdk

import "strconv"

type Variable byte

const (
	Variableundefined                              Variable = 0
	Variableapparent_temperature                   Variable = 1
	Variablecape                                   Variable = 2
	Variablecloud_cover                            Variable = 3
	Variablecloud_cover_high                       Variable = 4
	Variablecloud_cover_low                        Variable = 5
	Variablecloud_cover_mid                        Variable = 6
	Variabledaylight_duration                      Variable = 7
	Variabledew_point                              Variable = 8
	Variablediffuse_radiation                      Variable = 9
	Variablediffuse_radiation_instant              Variable = 10
	Variabledirect_normal_irradiance               Variable = 11
	Variabledirect_normal_irradiance_instant       Variable = 12
	Variabledirect_radiation                       Variable = 13
	Variabledirect_radiation_instant               Variable = 14
	Variableet0_fao_evapotranspiration             Variable = 15
	Variableevapotranspiration                     Variable = 16
	Variablefreezing_level_height                  Variable = 17
	Variablegrowing_degree_days                    Variable = 18
	Variableis_day                                 Variable = 19
	Variablelatent_heat_flux                       Variable = 20
	Variableleaf_wetness_probability               Variable = 21
	Variablelifted_index                           Variable = 22
	Variablelightning_potential                    Variable = 23
	Variableprecipitation                          Variable = 24
	Variableprecipitation_hours                    Variable = 25
	Variableprecipitation_probability              Variable = 26
	Variablepressure_msl                           Variable = 27
	Variablerain                                   Variable = 28
	Variablerelative_humidity                      Variable = 29
	Variablerunoff                                 Variable = 30
	Variablesensible_heat_flux                     Variable = 31
	Variableshortwave_radiation                    Variable = 32
	Variableshortwave_radiation_instant            Variable = 33
	Variableshowers                                Variable = 34
	Variablesnow_depth                             Variable = 35
	Variablesnow_height                            Variable = 36
	Variablesnowfall                               Variable = 37
	Variablesnowfall_height                        Variable = 38
	Variablesnowfall_water_equivalent              Variable = 39
	Variablesunrise                                Variable = 40
	Variablesunset                                 Variable = 41
	Variablesoil_moisture                          Variable = 42
	Variablesoil_moisture_index                    Variable = 43
	Variablesoil_temperature                       Variable = 44
	Variablesurface_pressure                       Variable = 45
	Variablesurface_temperature                    Variable = 46
	Variabletemperature                            Variable = 47
	Variableterrestrial_radiation                  Variable = 48
	Variableterrestrial_radiation_instant          Variable = 49
	Variabletotal_column_integrated_water_vapour   Variable = 50
	Variableupdraft                                Variable = 51
	Variableuv_index                               Variable = 52
	Variableuv_index_clear_sky                     Variable = 53
	Variablevapour_pressure_deficit                Variable = 54
	Variablevisibility                             Variable = 55
	Variableweather_code                           Variable = 56
	Variablewind_direction                         Variable = 57
	Variablewind_gusts                             Variable = 58
	Variablewind_speed                             Variable = 59
	Variablevertical_velocity                      Variable = 60
	Variablegeopotential_height                    Variable = 61
	Variablewet_bulb_temperature                   Variable = 62
	Variableriver_discharge                        Variable = 63
	Variablewave_height                            Variable = 64
	Variablewave_period                            Variable = 65
	Variablewave_direction                         Variable = 66
	Variablewind_wave_height                       Variable = 67
	Variablewind_wave_period                       Variable = 68
	Variablewind_wave_peak_period                  Variable = 69
	Variablewind_wave_direction                    Variable = 70
	Variableswell_wave_height                      Variable = 71
	Variableswell_wave_period                      Variable = 72
	Variableswell_wave_peak_period                 Variable = 73
	Variableswell_wave_direction                   Variable = 74
	Variablepm10                                   Variable = 75
	Variablepm2p5                                  Variable = 76
	Variabledust                                   Variable = 77
	Variableaerosol_optical_depth                  Variable = 78
	Variablecarbon_monoxide                        Variable = 79
	Variablenitrogen_dioxide                       Variable = 80
	Variableammonia                                Variable = 81
	Variableozone                                  Variable = 82
	Variablesulphur_dioxide                        Variable = 83
	Variablealder_pollen                           Variable = 84
	Variablebirch_pollen                           Variable = 85
	Variablegrass_pollen                           Variable = 86
	Variablemugwort_pollen                         Variable = 87
	Variableolive_pollen                           Variable = 88
	Variableragweed_pollen                         Variable = 89
	Variableeuropean_aqi                           Variable = 90
	Variableeuropean_aqi_pm2p5                     Variable = 91
	Variableeuropean_aqi_pm10                      Variable = 92
	Variableeuropean_aqi_nitrogen_dioxide          Variable = 93
	Variableeuropean_aqi_ozone                     Variable = 94
	Variableeuropean_aqi_sulphur_dioxide           Variable = 95
	Variableus_aqi                                 Variable = 96
	Variableus_aqi_pm2p5                           Variable = 97
	Variableus_aqi_pm10                            Variable = 98
	Variableus_aqi_nitrogen_dioxide                Variable = 99
	Variableus_aqi_ozone                           Variable = 100
	Variableus_aqi_sulphur_dioxide                 Variable = 101
	Variableus_aqi_carbon_monoxide                 Variable = 102
	Variablesunshine_duration                      Variable = 103
	Variableconvective_inhibition                  Variable = 104
	Variableshortwave_radiation_clear_sky          Variable = 105
	Variableglobal_tilted_irradiance               Variable = 106
	Variableglobal_tilted_irradiance_instant       Variable = 107
	Variableocean_current_velocity                 Variable = 108
	Variableocean_current_direction                Variable = 109
	Variablecloud_base                             Variable = 110
	Variablecloud_top                              Variable = 111
	Variablemass_density                           Variable = 112
	Variableboundary_layer_height                  Variable = 113
	Variableformaldehyde                           Variable = 114
	Variableglyoxal                                Variable = 115
	Variablenon_methane_volatile_organic_compounds Variable = 116
	Variablepm10_wildfires                         Variable = 117
	Variableperoxyacyl_nitrates                    Variable = 118
	Variablesecondary_inorganic_aerosol            Variable = 119
	Variableresidential_elementary_carbon          Variable = 120
	Variabletotal_elementary_carbon                Variable = 121
	Variablepm2_5_total_organic_matter             Variable = 122
	Variablesea_salt_aerosol                       Variable = 123
	Variablenitrogen_monoxide                      Variable = 124
	Variablethunderstorm_probability               Variable = 125
	Variablerain_probability                       Variable = 126
	Variablefreezing_rain_probability              Variable = 127
	Variableice_pellets_probability                Variable = 128
	Variablesnowfall_probability                   Variable = 129
	Variablecarbon_dioxide                         Variable = 130
	Variablemethane                                Variable = 131
)

var EnumNamesVariable = map[Variable]string{
	Variableundefined:                              "undefined",
	Variableapparent_temperature:                   "apparent_temperature",
	Variablecape:                                   "cape",
	Variablecloud_cover:                            "cloud_cover",
	Variablecloud_cover_high:                       "cloud_cover_high",
	Variablecloud_cover_low:                        "cloud_cover_low",
	Variablecloud_cover_mid:                        "cloud_cover_mid",
	Variabledaylight_duration:                      "daylight_duration",
	Variabledew_point:                              "dew_point",
	Variablediffuse_radiation:                      "diffuse_radiation",
	Variablediffuse_radiation_instant:              "diffuse_radiation_instant",
	Variabledirect_normal_irradiance:               "direct_normal_irradiance",
	Variabledirect_normal_irradiance_instant:       "direct_normal_irradiance_instant",
	Variabledirect_radiation:                       "direct_radiation",
	Variabledirect_radiation_instant:               "direct_radiation_instant",
	Variableet0_fao_evapotranspiration:             "et0_fao_evapotranspiration",
	Variableevapotranspiration:                     "evapotranspiration",
	Variablefreezing_level_height:                  "freezing_level_height",
	Variablegrowing_degree_days:                    "growing_degree_days",
	Variableis_day:                                 "is_day",
	Variablelatent_heat_flux:                       "latent_heat_flux",
	Variableleaf_wetness_probability:               "leaf_wetness_probability",
	Variablelifted_index:                           "lifted_index",
	Variablelightning_potential:                    "lightning_potential",
	Variableprecipitation:                          "precipitation",
	Variableprecipitation_hours:                    "precipitation_hours",
	Variableprecipitation_probability:              "precipitation_probability",
	Variablepressure_msl:                           "pressure_msl",
	Variablerain:                                   "rain",
	Variablerelative_humidity:                      "relative_humidity",
	Variablerunoff:                                 "runoff",
	Variablesensible_heat_flux:                     "sensible_heat_flux",
	Variableshortwave_radiation:                    "shortwave_radiation",
	Variableshortwave_radiation_instant:            "shortwave_radiation_instant",
	Variableshowers:                                "showers",
	Variablesnow_depth:                             "snow_depth",
	Variablesnow_height:                            "snow_height",
	Variablesnowfall:                               "snowfall",
	Variablesnowfall_height:                        "snowfall_height",
	Variablesnowfall_water_equivalent:              "snowfall_water_equivalent",
	Variablesunrise:                                "sunrise",
	Variablesunset:                                 "sunset",
	Variablesoil_moisture:                          "soil_moisture",
	Variablesoil_moisture_index:                    "soil_moisture_index",
	Variablesoil_temperature:                       "soil_temperature",
	Variablesurface_pressure:                       "surface_pressure",
	Variablesurface_temperature:                    "surface_temperature",
	Variabletemperature:                            "temperature",
	Variableterrestrial_radiation:                  "terrestrial_radiation",
	Variableterrestrial_radiation_instant:          "terrestrial_radiation_instant",
	Variabletotal_column_integrated_water_vapour:   "total_column_integrated_water_vapour",
	Variableupdraft:                                "updraft",
	Variableuv_index:                               "uv_index",
	Variableuv_index_clear_sky:                     "uv_index_clear_sky",
	Variablevapour_pressure_deficit:                "vapour_pressure_deficit",
	Variablevisibility:                             "visibility",
	Variableweather_code:                           "weather_code",
	Variablewind_direction:                         "wind_direction",
	Variablewind_gusts:                             "wind_gusts",
	Variablewind_speed:                             "wind_speed",
	Variablevertical_velocity:                      "vertical_velocity",
	Variablegeopotential_height:                    "geopotential_height",
	Variablewet_bulb_temperature:                   "wet_bulb_temperature",
	Variableriver_discharge:                        "river_discharge",
	Variablewave_height:                            "wave_height",
	Variablewave_period:                            "wave_period",
	Variablewave_direction:                         "wave_direction",
	Variablewind_wave_height:                       "wind_wave_height",
	Variablewind_wave_period:                       "wind_wave_period",
	Variablewind_wave_peak_period:                  "wind_wave_peak_period",
	Variablewind_wave_direction:                    "wind_wave_direction",
	Variableswell_wave_height:                      "swell_wave_height",
	Variableswell_wave_period:                      "swell_wave_period",
	Variableswell_wave_peak_period:                 "swell_wave_peak_period",
	Variableswell_wave_direction:                   "swell_wave_direction",
	Variablepm10:                                   "pm10",
	Variablepm2p5:                                  "pm2p5",
	Variabledust:                                   "dust",
	Variableaerosol_optical_depth:                  "aerosol_optical_depth",
	Variablecarbon_monoxide:                        "carbon_monoxide",
	Variablenitrogen_dioxide:                       "nitrogen_dioxide",
	Variableammonia:                                "ammonia",
	Variableozone:                                  "ozone",
	Variablesulphur_dioxide:                        "sulphur_dioxide",
	Variablealder_pollen:                           "alder_pollen",
	Variablebirch_pollen:                           "birch_pollen",
	Variablegrass_pollen:                           "grass_pollen",
	Variablemugwort_pollen:                         "mugwort_pollen",
	Variableolive_pollen:                           "olive_pollen",
	Variableragweed_pollen:                         "ragweed_pollen",
	Variableeuropean_aqi:                           "european_aqi",
	Variableeuropean_aqi_pm2p5:                     "european_aqi_pm2p5",
	Variableeuropean_aqi_pm10:                      "european_aqi_pm10",
	Variableeuropean_aqi_nitrogen_dioxide:          "european_aqi_nitrogen_dioxide",
	Variableeuropean_aqi_ozone:                     "european_aqi_ozone",
	Variableeuropean_aqi_sulphur_dioxide:           "european_aqi_sulphur_dioxide",
	Variableus_aqi:                                 "us_aqi",
	Variableus_aqi_pm2p5:                           "us_aqi_pm2p5",
	Variableus_aqi_pm10:                            "us_aqi_pm10",
	Variableus_aqi_nitrogen_dioxide:                "us_aqi_nitrogen_dioxide",
	Variableus_aqi_ozone:                           "us_aqi_ozone",
	Variableus_aqi_sulphur_dioxide:                 "us_aqi_sulphur_dioxide",
	Variableus_aqi_carbon_monoxide:                 "us_aqi_carbon_monoxide",
	Variablesunshine_duration:                      "sunshine_duration",
	Variableconvective_inhibition:                  "convective_inhibition",
	Variableshortwave_radiation_clear_sky:          "shortwave_radiation_clear_sky",
	Variableglobal_tilted_irradiance:               "global_tilted_irradiance",
	Variableglobal_tilted_irradiance_instant:       "global_tilted_irradiance_instant",
	Variableocean_current_velocity:                 "ocean_current_velocity",
	Variableocean_current_direction:                "ocean_current_direction",
	Variablecloud_base:                             "cloud_base",
	Variablecloud_top:                              "cloud_top",
	Variablemass_density:                           "mass_density",
	Variableboundary_layer_height:                  "boundary_layer_height",
	Variableformaldehyde:                           "formaldehyde",
	Variableglyoxal:                                "glyoxal",
	Variablenon_methane_volatile_organic_compounds: "non_methane_volatile_organic_compounds",
	Variablepm10_wildfires:                         "pm10_wildfires",
	Variableperoxyacyl_nitrates:                    "peroxyacyl_nitrates",
	Variablesecondary_inorganic_aerosol:            "secondary_inorganic_aerosol",
	Variableresidential_elementary_carbon:          "residential_elementary_carbon",
	Variabletotal_elementary_carbon:                "total_elementary_carbon",
	Variablepm2_5_total_organic_matter:             "pm2_5_total_organic_matter",
	Variablesea_salt_aerosol:                       "sea_salt_aerosol",
	Variablenitrogen_monoxide:                      "nitrogen_monoxide",
	Variablethunderstorm_probability:               "thunderstorm_probability",
	Variablerain_probability:                       "rain_probability",
	Variablefreezing_rain_probability:              "freezing_rain_probability",
	Variableice_pellets_probability:                "ice_pellets_probability",
	Variablesnowfall_probability:                   "snowfall_probability",
	Variablecarbon_dioxide:                         "carbon_dioxide",
	Variablemethane:                                "methane",
}

var EnumValuesVariable = map[string]Variable{
	"undefined":                              Variableundefined,
	"apparent_temperature":                   Variableapparent_temperature,
	"cape":                                   Variablecape,
	"cloud_cover":                            Variablecloud_cover,
	"cloud_cover_high":                       Variablecloud_cover_high,
	"cloud_cover_low":                        Variablecloud_cover_low,
	"cloud_cover_mid":                        Variablecloud_cover_mid,
	"daylight_duration":                      Variabledaylight_duration,
	"dew_point":                              Variabledew_point,
	"diffuse_radiation":                      Variablediffuse_radiation,
	"diffuse_radiation_instant":              Variablediffuse_radiation_instant,
	"direct_normal_irradiance":               Variabledirect_normal_irradiance,
	"direct_normal_irradiance_instant":       Variabledirect_normal_irradiance_instant,
	"direct_radiation":                       Variabledirect_radiation,
	"direct_radiation_instant":               Variabledirect_radiation_instant,
	"et0_fao_evapotranspiration":             Variableet0_fao_evapotranspiration,
	"evapotranspiration":                     Variableevapotranspiration,
	"freezing_level_height":                  Variablefreezing_level_height,
	"growing_degree_days":                    Variablegrowing_degree_days,
	"is_day":                                 Variableis_day,
	"latent_heat_flux":                       Variablelatent_heat_flux,
	"leaf_wetness_probability":               Variableleaf_wetness_probability,
	"lifted_index":                           Variablelifted_index,
	"lightning_potential":                    Variablelightning_potential,
	"precipitation":                          Variableprecipitation,
	"precipitation_hours":                    Variableprecipitation_hours,
	"precipitation_probability":              Variableprecipitation_probability,
	"pressure_msl":                           Variablepressure_msl,
	"rain":                                   Variablerain,
	"relative_humidity":                      Variablerelative_humidity,
	"runoff":                                 Variablerunoff,
	"sensible_heat_flux":                     Variablesensible_heat_flux,
	"shortwave_radiation":                    Variableshortwave_radiation,
	"shortwave_radiation_instant":            Variableshortwave_radiation_instant,
	"showers":                                Variableshowers,
	"snow_depth":                             Variablesnow_depth,
	"snow_height":                            Variablesnow_height,
	"snowfall":                               Variablesnowfall,
	"snowfall_height":                        Variablesnowfall_height,
	"snowfall_water_equivalent":              Variablesnowfall_water_equivalent,
	"sunrise":                                Variablesunrise,
	"sunset":                                 Variablesunset,
	"soil_moisture":                          Variablesoil_moisture,
	"soil_moisture_index":                    Variablesoil_moisture_index,
	"soil_temperature":                       Variablesoil_temperature,
	"surface_pressure":                       Variablesurface_pressure,
	"surface_temperature":                    Variablesurface_temperature,
	"temperature":                            Variabletemperature,
	"terrestrial_radiation":                  Variableterrestrial_radiation,
	"terrestrial_radiation_instant":          Variableterrestrial_radiation_instant,
	"total_column_integrated_water_vapour":   Variabletotal_column_integrated_water_vapour,
	"updraft":                                Variableupdraft,
	"uv_index":                               Variableuv_index,
	"uv_index_clear_sky":                     Variableuv_index_clear_sky,
	"vapour_pressure_deficit":                Variablevapour_pressure_deficit,
	"visibility":                             Variablevisibility,
	"weather_code":                           Variableweather_code,
	"wind_direction":                         Variablewind_direction,
	"wind_gusts":                             Variablewind_gusts,
	"wind_speed":                             Variablewind_speed,
	"vertical_velocity":                      Variablevertical_velocity,
	"geopotential_height":                    Variablegeopotential_height,
	"wet_bulb_temperature":                   Variablewet_bulb_temperature,
	"river_discharge":                        Variableriver_discharge,
	"wave_height":                            Variablewave_height,
	"wave_period":                            Variablewave_period,
	"wave_direction":                         Variablewave_direction,
	"wind_wave_height":                       Variablewind_wave_height,
	"wind_wave_period":                       Variablewind_wave_period,
	"wind_wave_peak_period":                  Variablewind_wave_peak_period,
	"wind_wave_direction":                    Variablewind_wave_direction,
	"swell_wave_height":                      Variableswell_wave_height,
	"swell_wave_period":                      Variableswell_wave_period,
	"swell_wave_peak_period":                 Variableswell_wave_peak_period,
	"swell_wave_direction":                   Variableswell_wave_direction,
	"pm10":                                   Variablepm10,
	"pm2p5":                                  Variablepm2p5,
	"dust":                                   Variabledust,
	"aerosol_optical_depth":                  Variableaerosol_optical_depth,
	"carbon_monoxide":                        Variablecarbon_monoxide,
	"nitrogen_dioxide":                       Variablenitrogen_dioxide,
	"ammonia":                                Variableammonia,
	"ozone":                                  Variableozone,
	"sulphur_dioxide":                        Variablesulphur_dioxide,
	"alder_pollen":                           Variablealder_pollen,
	"birch_pollen":                           Variablebirch_pollen,
	"grass_pollen":                           Variablegrass_pollen,
	"mugwort_pollen":                         Variablemugwort_pollen,
	"olive_pollen":                           Variableolive_pollen,
	"ragweed_pollen":                         Variableragweed_pollen,
	"european_aqi":                           Variableeuropean_aqi,
	"european_aqi_pm2p5":                     Variableeuropean_aqi_pm2p5,
	"european_aqi_pm10":                      Variableeuropean_aqi_pm10,
	"european_aqi_nitrogen_dioxide":          Variableeuropean_aqi_nitrogen_dioxide,
	"european_aqi_ozone":                     Variableeuropean_aqi_ozone,
	"european_aqi_sulphur_dioxide":           Variableeuropean_aqi_sulphur_dioxide,
	"us_aqi":                                 Variableus_aqi,
	"us_aqi_pm2p5":                           Variableus_aqi_pm2p5,
	"us_aqi_pm10":                            Variableus_aqi_pm10,
	"us_aqi_nitrogen_dioxide":                Variableus_aqi_nitrogen_dioxide,
	"us_aqi_ozone":                           Variableus_aqi_ozone,
	"us_aqi_sulphur_dioxide":                 Variableus_aqi_sulphur_dioxide,
	"us_aqi_carbon_monoxide":                 Variableus_aqi_carbon_monoxide,
	"sunshine_duration":                      Variablesunshine_duration,
	"convective_inhibition":                  Variableconvective_inhibition,
	"shortwave_radiation_clear_sky":          Variableshortwave_radiation_clear_sky,
	"global_tilted_irradiance":               Variableglobal_tilted_irradiance,
	"global_tilted_irradiance_instant":       Variableglobal_tilted_irradiance_instant,
	"ocean_current_velocity":                 Variableocean_current_velocity,
	"ocean_current_direction":                Variableocean_current_direction,
	"cloud_base":                             Variablecloud_base,
	"cloud_top":                              Variablecloud_top,
	"mass_density":                           Variablemass_density,
	"boundary_layer_height":                  Variableboundary_layer_height,
	"formaldehyde":                           Variableformaldehyde,
	"glyoxal":                                Variableglyoxal,
	"non_methane_volatile_organic_compounds": Variablenon_methane_volatile_organic_compounds,
	"pm10_wildfires":                         Variablepm10_wildfires,
	"peroxyacyl_nitrates":                    Variableperoxyacyl_nitrates,
	"secondary_inorganic_aerosol":            Variablesecondary_inorganic_aerosol,
	"residential_elementary_carbon":          Variableresidential_elementary_carbon,
	"total_elementary_carbon":                Variabletotal_elementary_carbon,
	"pm2_5_total_organic_matter":             Variablepm2_5_total_organic_matter,
	"sea_salt_aerosol":                       Variablesea_salt_aerosol,
	"nitrogen_monoxide":                      Variablenitrogen_monoxide,
	"thunderstorm_probability":               Variablethunderstorm_probability,
	"rain_probability":                       Variablerain_probability,
	"freezing_rain_probability":              Variablefreezing_rain_probability,
	"ice_pellets_probability":                Variableice_pellets_probability,
	"snowfall_probability":                   Variablesnowfall_probability,
	"carbon_dioxide":                         Variablecarbon_dioxide,
	"methane":                                Variablemethane,
}

func (v Variable) String() string {
	if s, ok := EnumNamesVariable[v]; ok {
		return s
	}
	return "Variable(" + strconv.FormatInt(int64(v), 10) + ")"
}
